// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2S3UzINERe5R35p_pL-E6PlZjlT_lF0g',
    appId: '1:226010952992:web:1b8c8c706889ab4cb69345',
    messagingSenderId: '226010952992',
    projectId: 'wecare-bma',
    authDomain: 'wecare-bma.firebaseapp.com',
    storageBucket: 'wecare-bma.appspot.com',
    measurementId: 'G-6LS4VR9FK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiq2y-XWtwJoSjNClSyGuKpyY6MBnSdLo',
    appId: '1:226010952992:android:fdb3b76af3c6f7fbb69345',
    messagingSenderId: '226010952992',
    projectId: 'wecare-bma',
    storageBucket: 'wecare-bma.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUwzTGk4wEYEyaRJFHY0v2ntJ_la3HbUQ',
    appId: '1:226010952992:ios:4ccf721ad60f4e5bb69345',
    messagingSenderId: '226010952992',
    projectId: 'wecare-bma',
    storageBucket: 'wecare-bma.appspot.com',
    iosClientId: '226010952992-p6ggprvv1071p17cnbprkd3bqki7rjmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.wecareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUwzTGk4wEYEyaRJFHY0v2ntJ_la3HbUQ',
    appId: '1:226010952992:ios:4ccf721ad60f4e5bb69345',
    messagingSenderId: '226010952992',
    projectId: 'wecare-bma',
    storageBucket: 'wecare-bma.appspot.com',
    iosClientId: '226010952992-p6ggprvv1071p17cnbprkd3bqki7rjmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.wecareApp',
  );
}
